Move code to `main()`
PHOTOX/promdens pull request #13
Opened 2024-09-05 15:42 UTC by danielhollas

This is a last PR that mostly just moves code. Now that all the code is out of global scope, we can make this into an importable module / package in next PR. 

This also exposed a couple of cases in `sample_initial_conditions()` method which relied on global variables.

2024-09-05 15:53 UTC, danielhollas commented on README.md
> -* `argparse`
These two modules are in standard library, so are always available, no need to mention them here.

2024-09-05 19:09 UTC, danielhollas commented on promdens.py
> +            (ics.field_omega + 2 * ics.field_lchirp * ics.field_t) / ics.evtoau,
Here I've switched from `omega` to `ics.field_omega` and `lchirp` to `ics.field_lchirp`.

2024-09-09 08:09 UTC, JanosJiri requested changes
Very nice, thanks for all the work! I located one or two typos, otherwise I see no problems with the code. I did a simple test and it worked.

I have only a small issue with some changes in formatting of a few lines of the code. I would keep input parameters of functions as one line of the code unless you have some objections against it. I use a autoformatting in PyCharm before every commit and it changes it back to the original one line structure. I would run it through the autoformatting in the future, which would remove that. Is it ok for you?

2024-09-09 08:34 UTC, danielhollas commented
@JanosJiri thanks for the review. Agree that formatting is a matter of taste and should be dealt separately. Ideally in the future we'd have autoformatter running automatically in CI so that the formatting doesn't depend on personal configurations. 

Personally I find that a lot of the lines in the current code are quite long. But again that's a matter of preference.

For now could you please autoformat the file according to your config and push to this branch. Feel free to fix the typos as well.

2024-09-09 09:39 UTC, JanosJiri commented
@danielhollas I see your point. Maybe it would be best to later find a way in between with the formatting. We can later set up a format to solve it. Thanks again for the work. I have changed the typos and I'm going to squash and merge the pull request.

2024-09-09 09:39 UTC, JanosJiri approved these changes

2024-09-09 09:39 UTC, merged